### ISSUE TITLE
Neo4j does not support PackStream parameters of type Timestamp

### ISSUE THREAD

**Issue by aguinaldoabbj** [py2neo-org/py2neo#786]
Hi all,

I'm struggling with a problem when merging nodes with a timestamp property. After setting a node property with a pandas datetime64 value, I've got the following error message when using tx.merge():

"Neo4j does not support PackStream parameters of type Timestamp"

If I cast the timestamp value to str, the process is well succeeded.

Why is that? Isn't Neo4j supposed to natively support date/times as node properties?

I'm using Neo4j 3.5.13, py2neo 4.3.0 and pandas 0.25.3.

Thanks in advance for any guidance.

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-104-8c508558338b> in <module>
      1 tic()
      2 tx = graph.begin()
----> 3 df.sample(100).apply(df_to_graph, axis=1)
      4 tx.commit()
      5 toc()

/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6926             kwds=kwds,
   6927         )
-> 6928         return op.get_result()
   6929 
   6930     def applymap(self, func):

/opt/conda/lib/python3.7/site-packages/pandas/core/apply.py in get_result(self)
    184             return self.apply_raw()
    185 
--> 186         return self.apply_standard()
    187 
    188     def apply_empty_result(self):

/opt/conda/lib/python3.7/site-packages/pandas/core/apply.py in apply_standard(self)
    290 
    291         # compute the result using the series generator
--> 292         self.apply_series_generator()
    293 
    294         # wrap results

/opt/conda/lib/python3.7/site-packages/pandas/core/apply.py in apply_series_generator(self)
    319             try:
    320                 for i, v in enumerate(series_gen):
--> 321                     results[i] = self.f(v)
    322                     keys.append(v.name)
    323             except Exception as e:

<ipython-input-103-fa3748b3fe7d> in df_to_graph(row)
     30     PATH=Path(Occur_Node,"IS_OCCURRENCE_OF",PATH)
     31 
---> 32     tx.merge(PATH)

/opt/conda/lib/python3.7/site-packages/py2neo/database.py in merge(self, subgraph, primary_label, primary_key)
    973             raise TypeError("No method defined to merge object %r" % subgraph)
    974         else:
--> 975             merge(self, primary_label, primary_key)
    976 
    977     def pull(self, subgraph):

/opt/conda/lib/python3.7/site-packages/py2neo/data.py in __db_merge__(self, tx, primary_label, primary_key)
    616 
    617     def __db_merge__(self, tx, primary_label=None, primary_key=None):
--> 618         merge_subgraph(tx, self, primary_label, primary_key)
    619 
    620     def __db_pull__(self, tx):

/opt/conda/lib/python3.7/site-packages/py2neo/internal/operations.py in merge_subgraph(tx, subgraph, p_label, p_key)
    165             raise ValueError("Primary label and primary key are required for MERGE operation")
    166         identities = _merge_nodes(tx, pl, pk, labels, list(map(lambda n: [n.get(pk), dict(n)], nodes)))
--> 167         for i, identity in enumerate(identities):
    168             node = nodes[i]
    169             node.graph = graph

/opt/conda/lib/python3.7/site-packages/py2neo/internal/operations.py in _merge_nodes(tx, p_label, p_key, labels, data)
    103     cypher = "UNWIND $x AS data MERGE (_:%s {%s:data[0]}) SET _:%s SET _ = data[1] RETURN id(_)" % (
    104         cypher_escape(p_label), cypher_escape(p_key), label_string)
--> 105     for record in tx.run(cypher, x=data):
    106         yield record[0]
    107 

/opt/conda/lib/python3.7/site-packages/py2neo/database.py in run(self, cypher, parameters, **kwparameters)
    826                                              graph=self.graph,
    827                                              keys=[],
--> 828                                              entities=entities))
    829         except CypherError as error:
    830             raise GraphError.hydrate({"code": error.code, "message": error.message})

/opt/conda/lib/python3.7/site-packages/py2neo/internal/connectors.py in run(self, statement, parameters, tx, graph, keys, entities)
    292             return self._run_1(statement, parameters, graph, keys, entities)
    293         else:
--> 294             return self._run_in_tx(statement, parameters, tx, graph, keys, entities)
    295 
    296     def begin(self):

/opt/conda/lib/python3.7/site-packages/py2neo/internal/connectors.py in _run_in_tx(self, statement, parameters, tx, graph, keys, entities)
    268 
    269         hydrator = PackStreamHydrator(version=tx.protocol_version, graph=graph, keys=keys, entities=entities)
--> 270         dehydrated_parameters = hydrator.dehydrate(parameters)
    271         result = CypherResult(on_more=fetch)
    272         result.update_metadata({"connection": self.connection_data})

/opt/conda/lib/python3.7/site-packages/py2neo/internal/hydration/__init__.py in dehydrate(self, data)
    294                 if not isinstance(key, string_types):
    295                     raise TypeError("Dictionary keys must be strings")
--> 296                 d[key] = self.dehydrate(data[key])
    297             return d
    298         elif isinstance(data, Sequence):

/opt/conda/lib/python3.7/site-packages/py2neo/internal/hydration/__init__.py in dehydrate(self, data)
    297             return d
    298         elif isinstance(data, Sequence):
--> 299             return list(map(self.dehydrate, data))
    300         else:
    301             raise TypeError("Neo4j does not support PackStream parameters of type %s" % type(data).__name__)

/opt/conda/lib/python3.7/site-packages/py2neo/internal/hydration/__init__.py in dehydrate(self, data)
    297             return d
    298         elif isinstance(data, Sequence):
--> 299             return list(map(self.dehydrate, data))
    300         else:
    301             raise TypeError("Neo4j does not support PackStream parameters of type %s" % type(data).__name__)

/opt/conda/lib/python3.7/site-packages/py2neo/internal/hydration/__init__.py in dehydrate(self, data)
    294                 if not isinstance(key, string_types):
    295                     raise TypeError("Dictionary keys must be strings")
--> 296                 d[key] = self.dehydrate(data[key])
    297             return d
    298         elif isinstance(data, Sequence):

/opt/conda/lib/python3.7/site-packages/py2neo/internal/hydration/__init__.py in dehydrate(self, data)
    299             return list(map(self.dehydrate, data))
    300         else:
--> 301             raise TypeError("Neo4j does not support PackStream parameters of type %s" % type(data).__name__)
    302 
    303 

TypeError: ('Neo4j does not support PackStream parameters of type Timestamp', 'occurred at index 650398')
`

**Comment by derbytau** [comment]
Hello,

this might be a bit late but because I also struggled with this issue today so maybe this can help: 

I had the same issue with pandas and py2neo and I solved this issue by converting the pandas datetime to normal python datetime by calling `.to_pydatetime()` on the datetime before passing it to py2neo.
But I think it would be great if py2neo would support pandas because its a library that is really often used in python projects or at least a more suitable error message, that maybe could suggest converting the object to a python datetime

greetings derbytau

**Comment by technige** [comment]
Having checked today, pandas `Timestamp` extends the built-in `datetime` type. Therefore, this works when used for property values, and this issue can be closed.
