### ISSUE TITLE
Cannot get Node.graph

### ISSUE THREAD

**Issue by MelvinZang** [py2neo-org/py2neo#891]
I want to update node properties, so I ran the following code
```
g = get_graph()
nodes = NodeMatcher(g)
result = nodes.match(label, **param_dict).first()
result.update({'k': 'v'})
    g.push(n)
```

But I failed. Then I found `result.graph` was None, so I tried 
`result.graph = g`.
It failed again, `result.graph` was still None
Not sure if my attempt is correct.

**Comment by technige** [comment]
Can you expand on "failed"?

**Comment by technige** [comment]
Closing issue due to lack of information.
