### ISSUE TITLE
No `__all__` in `database`

### ISSUE THREAD

**Issue by StrangeTcy** [py2neo-org/py2neo#899]
A freshly installed py2neo on Ubuntu 18.04, when I try to run a python script with a line
> from py2neo import Graph, Node, Relationship, GraphService                    

run into the following error:                                                            

```
 File "/usr/local/lib/python3.6/dist-packages/py2neo/__init__.py", line 77, in <module>                                                      
  __all__ += database.__all__   
 AttributeError: module 'py2neo.database' has no attribute '__all__'    
```

Am I doing something wrong? What is supposed to be in `database.__all__`?

**Comment by technige** [comment]
I can't recreate what you see

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from py2neo import Graph, Node, Relationship, GraphService

In [2]: 
```

**Comment by technige** [comment]
Closing issue as unable to recreate.
