### ISSUE TITLE
running py2neo with threading lock() and queue freeze on create relationship  

### ISSUE THREAD

**Issue by trimbilrepo** [py2neo-org/py2neo#902]
I have experiencing some issue when creating relationship using thread.

simplify of my code

```python
import queue
import threading
from py2neo import Graph
GRAPH_HOST = "bolt://localhost:7687"
GRAPH_PASS = "......."

exitFlag	= 0
threadList 	= ["Thread-1","Thread-2", "Thread-3"]
queueLock 	= threading.Lock()
workQueue 	= queue.Queue(20000)

class myThread (threading.Thread):
  def __init__(self):
    threading.Thread.__init__(self)
    pass

  def run(self):
    graph_consumer()

def graph_consumer():
  while True:
   if not redisQueue.isEmpty():
     data = redisQueue.get()
     userid = data['userid']
     item_id = data['item_id']
     graph.run(f"MATCH (n:Person {{userid:{userid}}) MATCH (m:Item {{item_id:{item_id}}) MERGE (n)-[a:buyer]->(m) return n.name")
```
that query will freeze my script. it only affected on creating relationship, creating node working fine.

I guess there is something with threading.Lock() or queue.Queue() function. Since actually I did not use threading.Lock()  and queue.Queue() , it just junk in my code (copy-paste from old script).
after I remove those two lines, it working great.

**Comment by technige** [comment]
This is unlikely to be a specific problem with py2neo, although if you can narrow it down to code that can be used an a test, please reopen the issue.

Note also that `graph.run` results should be consumed. You are `RETURN`ing values, but not using them.
