### ISSUE TITLE
ProcedureNotFound __getstate__

### ISSUE THREAD

**Issue by apacha** [py2neo-org/py2neo#910]
Hi, 

we've been using py2neo for a while (4.3.0) and I wanted to upgrade the library to a later version, however, I'm getting this weird error in any more recent version that does not make a lot of sense to me:

```
py2neo.database.work.ClientError: [Procedure.ProcedureNotFound] There is no procedure with the name `__getstate__` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed. 
```

We're running neo4j in a docker container in version 4.1.4.

Is there any upgrade manual for py2neo or can you help me figuring out what the underlying problem is here and how to solve it?

**Comment by technige** [comment]
That is an error being returned by the server after being told to run a procedure called `__getstate__` which obviously doesn't exist as a procedure. Indeed that actually looks like a Python function name instead.

What code are you running that invokes this?

**Comment by apacha** [comment]
Never mind. I think the problem was something else. If I can reproduce the problem and have some code to reproduce it with, I will re-open a new ticket. 
Thanks!

**Comment by hajarmerbouh** [comment]
> 

I have almost the same issue, even tho I've successfully installed the library and it works perfectly on neo4j browser. But, when I call it in my jupyter notebook ( I'm working with py2neo)  it give the same error : [Procedure.ProcedureNotFound] .  

Did you find the solution? or the cause of the issue?
