### ISSUE TITLE
merge oncreate and onupdate

### ISSUE THREAD

**Issue by priamai** [py2neo-org/py2neo#928]
Hi folks,
love this library and would like to know (maybe I missed it) whether it is possible to call programmatically the MERGE operation with the ON CREATE and ON UPDATE events like [this from documentation](https://neo4j.com/docs/cypher-manual/current/clauses/merge/#merge-merge-with-on-create-and-on-match).
I use your batch mode quit a lot but now I need to distinguish between a new node created and one updated.
Great stuff, keep going!

**Comment by priamai** [comment]
Just to be more clear:
```

from py2neo import Graph
from py2neo.bulk import merge_nodes
g = Graph()
keys = ["name", "age"]
data = [
    ["Alice", 33],
    ["Bob", 44],
    ["Carol", 55],
    ["Carol", 66],
    ["Alice", 77],
]
merge_nodes(g.auto(), data, ("Person", "name"), keys=keys)
g.nodes.match("Person").count()

```

But maybe expand it like:

```
from py2neo import Graph
from py2neo.bulk import merge_nodes
g = Graph()
keys = ["name", "age"]
data = [
    ["Alice", 33],
    ["Bob", 44],
    ["Carol", 55],
    ["Carol", 66],
    ["Alice", 77],
]
merge_nodes(g.auto(), data, ("Person", "name"), keys=keys,oncreate=("first_age","age"),onupdate=("last_age","age"))
g.nodes.match("Person").count()
```

Would be nice to have the oncreate and onupdate working with a lambda function too but not sure whether that is realistic.

**Comment by technige** [comment]
Unfortunately, this isn't really possible. The event handlers would need to exist in the Cypher code, not as Python functions. So you'll need to drop down into writing this in pure Cypher instead. For reference, the higher-level wrapper functions were never intended to be comprehensive in terms of functionality, but merely helpers for common use cases.

**Comment by priamai** [comment]
Yes I totally understand, another possible solution would be to keep that syntax but maybe auto generate the cypher query under the hood?
It's not a big deal for me, I use the language quite often, but maybe fore less experienced users could be nice to have.

**Comment by technige** [comment]
Thanks for the suggestion. I don't plan to add anything like this at this time though.
