### ISSUE TITLE
DeprecationWarning: The transaction.commit() method is deprecated

### ISSUE THREAD

**Issue by priamai** [py2neo-org/py2neo#929]
Running:

```
Name: py2neo
Version: 2021.2.3
Summary: Python client library and toolkit for Neo4j
Home-page: https://py2neo.org/
Author: Nigel Small
Author-email: technige@py2neo.org
License: Apache License, Version 2.0
Location: /opt/conda/lib/python3.9/site-packages
Requires: certifi, packaging, six, urllib3, pansi, monotonic, interchange, pygments
Required-by: 
```

In the example pages:

>>> from py2neo import Graph, Node, Relationship
>>> g = Graph()
>>> tx = g.begin()
>>> a = Node("Person", name="Alice")
>>> tx.create(a)
>>> b = Node("Person", name="Bob")
>>> ab = Relationship(a, "KNOWS", b)
>>> tx.create(ab)
>>> tx.commit()
>>> g.exists(ab)

But I get:

DeprecationWarning: The transaction.commit() method is deprecated, use graph.commit(transaction) instead   tx.commit().

What's the new way of doing transactions?

**Comment by priamai** [comment]
It seems like this should be instead the example:
```

graph.delete_all()
tx = graph.begin()
a = Node("Person", name="Alice")
tx.create(a)
b = Node("Person", name="Bob")
ab = Relationship(a, "KNOWS", b)
tx.create(ab)
graph.commit(tx)
graph.exists(ab)
```
Which returns True.

**Comment by technige** [comment]
This is correct. As the warning states, the `commit` and `rollback` methods were moved to the `Graph` object. This was so that they sat alongside the `begin` method, keeping all transaction management operations in the same place.
