### ISSUE TITLE
make Property.__get__ return self if instance is None

### ISSUE THREAD

**Issue by gemerden** [py2neo-org/py2neo#936]
Currently the property descriptor cannot be called on the owner class, with error: `AttributeError: 'NoneType' object has no attribute '__node__'`. Calling the property on the class can be very useful for introspection. Also it is easily fixed bij changing:
```
class Property(object):
    def __get__(self, instance, owner):
        value = instance.__node__[self.key]
        if value is None:
            value = self.default
        return value
```
in:
```
class Property(object):
    def __get__(self, instance, owner):
        if instance is None:
            return self
        value = instance.__node__[self.key]
        if value is None:
            value = self.default
        return value
```
This is very common in descriptors.

**Comment by motey** [comment]
dup https://github.com/py2neo-org/py2neo/issues/784
