### ISSUE TITLE
add_label don't work

### ISSUE THREAD

**Issue by Jumbo-WJB** [py2neo-org/py2neo#939]
Hello, I am trying the add_label method:
`ToIPs.add_label("FromIPs")`
![1](https://user-images.githubusercontent.com/7954518/155090544-2b945d55-e216-4fcd-8565-df9c36e49a22.png)

 through `print(ToIPs.labels)` you can see that I already have two labels(FromIPs:ToIPs),
![2](https://user-images.githubusercontent.com/7954518/155090555-76eee054-afdc-470f-97ed-f30b0c5c99c1.png)
 but from neo4j and `print(ToIPs.labels) ` still only have one ToIPs label
![4](https://user-images.githubusercontent.com/7954518/155090571-b5b8905e-e91e-4387-9d15-9693ee18be25.png)

**Comment by motey** [comment]
Hi @Jumbo-WJB 

you will need to send your changes back to the database with `py2neo.Graph.push`

```python
import py2neo

g = py2neo.Graph()
myNode: py2neo.Node = g.run("CREATE (n:MyNode) RETURN n").data()[0]["n"]
myNode.add_label("mySecondLabel")
g.push(myNode)
```

Feedback for you Issue: If possible please provide functioning code snippets encapsulation your problem. And please do not provide screenshots of your code. that would be great.
