### ISSUE TITLE
Hardcoded self reference name in Subgraph

### ISSUE THREAD

**Issue by motey** [py2neo-org/py2neo#940]
When inheriting `py2neo.Subgraph` like this
```python3
from py2neo import Subgraph, Node
class CustomSG(Subgraph):
    def my_print_nodes_only(self):
        print(self.nodes)
```
 and using the build in operators on my custom class i wil get back a `py2neo.Subgraph` instead of my custom class.
example

```python3
cust_sb = CustomSG([Node("test")])
print(type(cust_sb))
cust_sb2 = CustomSG([Node("test")])
print(type(cust_sb2))
```
`>> <class '__main__.CustomSG'>`
`>> <class '__main__.CustomSG'>`
```python3
print(type(cust_sb | cust_sb2))
```
`>> <class 'py2neo.data.Subgraph'>`

I would expect to get back an object of my custom `Subgraph` class

This behavior happens because the operator functions have a hardcoded reference to the `py2neo.Subgraph` instead of a reference to the objects class.

See:  https://github.com/py2neo-org/py2neo/blob/master/py2neo/data.py#L149
```python
def __or__(self, other):
        return Subgraph(set(self.nodes) | set(other.nodes), set(self.relationships) | set(other.relationships))
```

**Comment by technige** [comment]
This class deliberately functions in this way, as subclasses such as Node and Relationship need to return a plain Subgraph when combined.

It is not intended for the user to subclass Subgraph.

**Comment by motey** [comment]
ok, i see.

A workaround for anybody having a similar issue:

```python
from py2neo import Subgraph, Node
class CustomSG(Subgraph):
    def my_print_nodes_only(self):
        print(self.nodes)

cust_sb = CustomSG([Node("test")])
cust_sb2 = CustomSG([Node("test")])

# this will generate a py2neo.Subgraph
sb: Subgraph = cust_sb2 | cust_sb
# lets convert it back to our custom class
sb_as_custom_class = CustomSG(nodes=sb.nodes, relationships=sb.relationships)
# now we can use our custom method
sb_as_custom_class.my_print_nodes_only()
```
