### ISSUE TITLE
Compatibility with neo4j version 5

### ISSUE THREAD

**Issue by bioinformaticaInta** [py2neo-org/py2neo#955]
Hi everyone, We are working with the new version of neo4j (version 5). Are you working in the adaptation of py2neo package for this new version??
Thanks

**Comment by Say1ts** [comment]
Также интересует этот вопрос

**Comment by technige** [comment]
There will be no more releases of py2neo, the project is now EOL. Please see https://github.com/py2neo-org/py2neo/issues/958#issuecomment-1554088585.
